Cage
Sanyyouisf/treehouse-cage-match pull request #2
Opened 2017-04-21 01:36 UTC by Sanyyouisf

2017-04-23 08:13 UTC, Sanyyouisf commented
@drdreed
finish

2017-04-24 22:07 UTC, drdreed commented on javascripts/main.js
> +                $.ajax("https://teamtreehouse.com/sanyyousif.json")
This is always the same user.  It does not take from the input field.

2017-04-24 22:07 UTC, drdreed commented on javascripts/main.js
> +                $.ajax("https://teamtreehouse.com/ellisthomas.json")
Same thing here.

2017-04-24 22:08 UTC, drdreed commented on javascripts/main.js
> +                $("#winner").val((players[0].name)+ "winns");
spelling on wins

2017-04-24 22:08 UTC, DevDreed requested changes
Please see the changes I have requested.

2017-04-24 22:16 UTC, Sanyyouisf commented on javascripts/main.js
> +                $("#winner").val((players[0].name)+ "winns");
@drdreed
right I will change it .
thanks

2017-04-25 00:20 UTC, Sanyyouisf commented
@drdreed
finish

2017-04-25 00:50 UTC, drdreed commented
👍

2017-04-25 21:08 UTC, merged